import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MainFrame extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    //스케줄 탭에서 id를 가져오는 리스트
    private ArrayList<Integer> scheduleIds = new ArrayList<>();

    //활동 내역 탭에서 id를 가져오는 리스트
    private ArrayList<Integer> activityIds = new ArrayList<>();

    //회비 관리 탭에서 id를 가져오는 리스트
    private ArrayList<Integer> duesIds = new ArrayList<>();

    // 스케줄 수정 모드 관련
    private boolean isEditMode = false;
    private int editingScheduleId = -1;

    public MainFrame() {
        initComponents();

        // 로그인 체크
        if (!UserSession.isLoggedIn()) {
            new LoginFrame().setVisible(true);
            dispose();
            return;
        }

        // 로그인된 사용자 이름 표시
        String userName = UserSession.getUserName();
        lblUserInfo.setText(userName + "님 환영합니다!");

        // 회원 테이블 로드
        loadMemberTable();
        loadScheduleTable();
        loadHistoryTable();
        loadDuesHistory();

        // 회비 관련 초기화
        loadMembersForRepresentative();
        setDefaultDuesDate(); // 회비 날짜 기본값 설정
        updateDuesLabels();

        // 스케줄 관련 초기화
        setDefaultScheDate(); // 스케줄 날짜 기본값 설정

        String role = UserSession.getRole();
        applyRoleBasedTabs(role);

        // 성별 필터 체크박스 리스너 추가
        setupGenderFilters();

        // 활동 내역 정렬 체크박스 리스너 추가
        setupActivitySortFilters();

        // 스케줄 정렬 체크박스 리스너 추가
        setupScheduleSortFilters();

        // 회비 정렬 체크박스 리스너 추가
        setupDuesSortFilters();

        // 테이블 단일 행 선택 모드 설정
        MemTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ScheTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        HisTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        DuesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        MemPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MemTable = new javax.swing.JTable();
        btnMemUpdate = new javax.swing.JButton();
        btnMemInsert = new javax.swing.JButton();
        btnMemDelete = new javax.swing.JButton();
        btnMemRefresh = new javax.swing.JButton();
        chkAll = new javax.swing.JCheckBox();
        chkMale = new javax.swing.JCheckBox();
        chkFemale = new javax.swing.JCheckBox();
        btnRoleChange = new javax.swing.JButton();
        SchePanel = new javax.swing.JPanel();
        btnScheInsert = new javax.swing.JButton();
        btnScheDelete = new javax.swing.JButton();
        txtScheYear = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        snpScheLocation = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtScheDay = new javax.swing.JTextField();
        txtScheMonth = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        snpScheDescription = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        chkScheCompleted = new javax.swing.JCheckBox();
        jScrollPane6 = new javax.swing.JScrollPane();
        ScheTable = new javax.swing.JTable();
        btnScheRefresh = new javax.swing.JButton();
        btnPartInsert = new javax.swing.JButton();
        chkScheLatest = new javax.swing.JCheckBox();
        chkScheDateOrder = new javax.swing.JCheckBox();
        btnScheUpdate = new javax.swing.JButton();
        DuesPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        DuesTable = new javax.swing.JTable();
        btnDuesInsert = new javax.swing.JButton();
        btnDuesUpdate = new javax.swing.JButton();
        btnDuesDelete = new javax.swing.JButton();
        txtDuesLocation = new javax.swing.JTextField();
        cbxDuesRepresentive = new javax.swing.JComboBox<>();
        txtDuesDescription = new javax.swing.JTextField();
        txtDuesAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDuesMonth = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDuesDay = new javax.swing.JTextField();
        txtDuesYear = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblTotalDues = new javax.swing.JLabel();
        lblRemainDues = new javax.swing.JLabel();
        btnDuesDeposit = new javax.swing.JButton();
        chkDuesDateOrder = new javax.swing.JCheckBox();
        chkDuesLatest = new javax.swing.JCheckBox();
        HisPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        HisTable = new javax.swing.JTable();
        btnHisDelete = new javax.swing.JButton();
        btnHisRefresh = new javax.swing.JButton();
        chkHisDateOrder = new javax.swing.JCheckBox();
        chkHisLatest = new javax.swing.JCheckBox();
        lblUserInfo = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainFrame");

        jScrollPane1.setBorder(null);

        MemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "아이디", "이름", "학번", "성별", "직책", "생년월일"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(MemTable);

        btnMemUpdate.setText("회원 수정");
        btnMemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemUpdateActionPerformed(evt);
            }
        });

        btnMemInsert.setText("회원 추가");
        btnMemInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemInsertActionPerformed(evt);
            }
        });

        btnMemDelete.setText("회원 삭제");
        btnMemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemDeleteActionPerformed(evt);
            }
        });

        btnMemRefresh.setText("새로고침");
        btnMemRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemRefreshActionPerformed(evt);
            }
        });

        buttonGroupGender.add(chkAll);
        chkAll.setSelected(true);
        chkAll.setText("전체");

        buttonGroupGender.add(chkMale);
        chkMale.setText("남자");

        buttonGroupGender.add(chkFemale);
        chkFemale.setText("여자");

        btnRoleChange.setText("직책 변경");
        btnRoleChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoleChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MemPanelLayout = new javax.swing.GroupLayout(MemPanel);
        MemPanel.setLayout(MemPanelLayout);
        MemPanelLayout.setHorizontalGroup(
            MemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemPanelLayout.createSequentialGroup()
                .addGroup(MemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MemPanelLayout.createSequentialGroup()
                        .addComponent(chkAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkFemale)
                        .addGap(0, 633, Short.MAX_VALUE))
                    .addGroup(MemPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMemUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMemInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMemDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRoleChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMemRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        MemPanelLayout.setVerticalGroup(
            MemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAll)
                    .addComponent(chkMale)
                    .addComponent(chkFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addGroup(MemPanelLayout.createSequentialGroup()
                        .addComponent(btnMemRefresh)
                        .addGap(18, 18, 18)
                        .addComponent(btnMemInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMemUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRoleChange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMemDelete)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("인원 관리", MemPanel);

        btnScheInsert.setText("일정 등록");
        btnScheInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheInsertActionPerformed(evt);
            }
        });

        btnScheDelete.setText("일정 삭제");
        btnScheDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheDeleteActionPerformed(evt);
            }
        });

        txtScheYear.setText("2025");
        txtScheYear.setToolTipText("");

        jLabel1.setText("년");

        jLabel2.setText("장소  : ");

        jLabel4.setText("월");

        jLabel5.setText("일");

        snpScheDescription.setColumns(20);
        snpScheDescription.setRows(1);
        snpScheDescription.setTabSize(1);
        jScrollPane3.setViewportView(snpScheDescription);

        jLabel6.setText("활동 내용  : ");

        chkScheCompleted.setText("완료");

        ScheTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "날짜", "장소", "인원 수", "활동 내용", "참가 인원", "완료"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScheTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScheTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(ScheTable);

        btnScheRefresh.setText("새로고침");
        btnScheRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheRefreshActionPerformed(evt);
            }
        });

        btnPartInsert.setText("인원 등록");
        btnPartInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartInsertActionPerformed(evt);
            }
        });

        chkScheLatest.setText("최신순");

        chkScheDateOrder.setText("날짜순");

        btnScheUpdate.setText("일정 수정");
        btnScheUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SchePanelLayout = new javax.swing.GroupLayout(SchePanel);
        SchePanel.setLayout(SchePanelLayout);
        SchePanelLayout.setHorizontalGroup(
            SchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SchePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SchePanelLayout.createSequentialGroup()
                        .addGroup(SchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SchePanelLayout.createSequentialGroup()
                                .addComponent(txtScheYear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtScheMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtScheDay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SchePanelLayout.createSequentialGroup()
                                .addComponent(chkScheDateOrder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkScheLatest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(snpScheLocation)
                            .addComponent(jScrollPane3))
                        .addGap(23, 23, 23)
                        .addComponent(chkScheCompleted)
                        .addGap(16, 16, 16))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnScheInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnScheDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnScheUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPartInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnScheRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        SchePanelLayout.setVerticalGroup(
            SchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SchePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SchePanelLayout.createSequentialGroup()
                        .addGroup(SchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(snpScheLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(SchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(SchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(chkScheDateOrder)
                                .addComponent(chkScheLatest))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkScheCompleted))
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addGroup(SchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SchePanelLayout.createSequentialGroup()
                                .addComponent(btnScheRefresh)
                                .addGap(18, 18, 18)
                                .addComponent(btnScheInsert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPartInsert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnScheUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnScheDelete))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SchePanelLayout.createSequentialGroup()
                        .addGroup(SchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtScheYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(txtScheDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtScheMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("스케줄 관리", SchePanel);

        DuesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "날짜", "장소", "사용 대표자", "사용 목적", "금액", "잔액"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(DuesTable);

        btnDuesInsert.setText("내역 추가");
        btnDuesInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuesInsertActionPerformed(evt);
            }
        });

        btnDuesUpdate.setText("새로고침");
        btnDuesUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuesUpdateActionPerformed(evt);
            }
        });

        btnDuesDelete.setText("내역 삭제");
        btnDuesDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuesDeleteActionPerformed(evt);
            }
        });

        cbxDuesRepresentive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("년");

        jLabel8.setText("장소 :");

        jLabel9.setText("대표자 :");

        jLabel10.setText("사용 내역 :");

        jLabel11.setText("금액 :");

        jLabel12.setText("월");

        jLabel13.setText("일");

        txtDuesYear.setText("2025");

        jLabel15.setText("잔여 회비 :");

        jLabel16.setText("이번 달 회비 :");

        lblTotalDues.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblTotalDues.setText("text");

        lblRemainDues.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblRemainDues.setText("text");

        btnDuesDeposit.setText("입금");
        btnDuesDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuesDepositActionPerformed(evt);
            }
        });

        chkDuesDateOrder.setText("날짜순");

        chkDuesLatest.setText("최신순");

        javax.swing.GroupLayout DuesPanelLayout = new javax.swing.GroupLayout(DuesPanel);
        DuesPanel.setLayout(DuesPanelLayout);
        DuesPanelLayout.setHorizontalGroup(
            DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DuesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DuesPanelLayout.createSequentialGroup()
                        .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DuesPanelLayout.createSequentialGroup()
                                .addComponent(txtDuesYear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDuesMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDuesDay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(DuesPanelLayout.createSequentialGroup()
                                .addComponent(chkDuesDateOrder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkDuesLatest)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(DuesPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDuesLocation)
                            .addComponent(txtDuesDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DuesPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtDuesAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DuesPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDuesRepresentive, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DuesPanelLayout.createSequentialGroup()
                                .addComponent(lblTotalDues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDuesDeposit))
                            .addComponent(lblRemainDues, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DuesPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDuesUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDuesInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDuesDelete))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DuesPanelLayout.setVerticalGroup(
            DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DuesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DuesPanelLayout.createSequentialGroup()
                        .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(lblTotalDues)
                                .addComponent(btnDuesDeposit))
                            .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txtDuesAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lblRemainDues)))
                    .addGroup(DuesPanelLayout.createSequentialGroup()
                        .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txtDuesLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtDuesYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDuesMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(txtDuesDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chkDuesDateOrder)
                                .addComponent(chkDuesLatest))
                            .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDuesDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(cbxDuesRepresentive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DuesPanelLayout.createSequentialGroup()
                        .addComponent(btnDuesUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDuesInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDuesDelete)
                        .addContainerGap(252, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("회비 관리", DuesPanel);

        HisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "날짜", "장소", "참가 인원 수", "활동 내용", "참가자"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(HisTable);

        btnHisDelete.setText("활동 삭제");
        btnHisDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHisDeleteActionPerformed(evt);
            }
        });

        btnHisRefresh.setText("새로고침");
        btnHisRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHisRefreshActionPerformed(evt);
            }
        });

        chkHisDateOrder.setText("날짜순");

        chkHisLatest.setText("최신순");

        javax.swing.GroupLayout HisPanelLayout = new javax.swing.GroupLayout(HisPanel);
        HisPanel.setLayout(HisPanelLayout);
        HisPanelLayout.setHorizontalGroup(
            HisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HisPanelLayout.createSequentialGroup()
                .addGroup(HisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HisPanelLayout.createSequentialGroup()
                        .addComponent(chkHisDateOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkHisLatest)
                        .addGap(0, 666, Short.MAX_VALUE))
                    .addGroup(HisPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHisDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHisRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        HisPanelLayout.setVerticalGroup(
            HisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHisDateOrder)
                    .addComponent(chkHisLatest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addGroup(HisPanelLayout.createSequentialGroup()
                        .addComponent(btnHisRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHisDelete)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("활동 내역", HisPanel);

        lblUserInfo.setText("admin님 환영합니다!");

        btnLogout.setText("로그아웃");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUserInfo)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(lblUserInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("인원 관리");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void applyRoleBasedTabs(String role) {
        // 관리자,부장이면 모두 보임
        if (role.equals("admin") || role.equals("president")) { return; }
        
        // 일반 회원(member)일 경우 숨길 버튼들
        btnMemInsert.setVisible(false);
        btnMemUpdate.setVisible(false);
        btnMemDelete.setVisible(false);
        btnRoleChange.setVisible(false);

        btnDuesInsert.setVisible(false);
        btnDuesUpdate.setVisible(false);
        btnDuesDelete.setVisible(false);
    }
    
    
    // 회원 테이블 로드
    private void loadMemberTable() {
        DefaultTableModel model = (DefaultTableModel) MemTable.getModel();
        model.setRowCount(0); // 초기화
        
        String sql = "SELECT id, username, name, student_id, gender, role, birth_date FROM users";

        DBConnection db = new DBConnection();

        // try-with-resources: Connection, PreparedStatement, ResultSet 자동 닫기
        try (Connection conn = db.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                String role = rs.getString("role");
                String roleKorean = convertRoleToKorean(role);

                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("username"),
                    rs.getString("name"),
                    rs.getString("student_id"),
                    rs.getString("gender"),
                    roleKorean,
                    rs.getString("birth_date")
                });
            }
        } catch (SQLException e) {
            System.err.println("회원 테이블 로드 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // 성별 필터에 따라 회원 테이블 로드
    private void loadMemberTableByGender(String gender) {
        DefaultTableModel model = (DefaultTableModel) MemTable.getModel();
        model.setRowCount(0); // 초기화

        String sql;
        if ("전체".equals(gender)) {
            sql = "SELECT id, username, name, student_id, gender, role, birth_date FROM users";
        } else {
            sql = "SELECT id, username, name, student_id, gender, role, birth_date FROM users WHERE gender = ?";
        }

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            // 전체가 아닌 경우에만 파라미터 설정
            if (!"전체".equals(gender)) {
                pstmt.setString(1, gender);
            }

            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    String role = rs.getString("role");
                    String roleKorean = convertRoleToKorean(role);

                    model.addRow(new Object[]{
                        rs.getInt("id"),
                        rs.getString("username"),
                        rs.getString("name"),
                        rs.getString("student_id"),
                        rs.getString("gender"),
                        roleKorean,
                        rs.getString("birth_date")
                    });
                }
            }
        } catch (SQLException e) {
            System.err.println("회원 테이블 로드 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // 현재 선택된 성별 필터에 따라 테이블 새로고침
    private void refreshMemberTable() {
        String selectedGender = "전체";
        if (chkMale.isSelected()) {
            selectedGender = "남";
        } else if (chkFemale.isSelected()) {
            selectedGender = "여";
        }
        loadMemberTableByGender(selectedGender);
    }

    // 성별 필터 체크박스 리스너 설정
    private void setupGenderFilters() {
        chkAll.addActionListener(e -> refreshMemberTable());
        chkMale.addActionListener(e -> refreshMemberTable());
        chkFemale.addActionListener(e -> refreshMemberTable());
    }

    // 활동 내역 정렬 체크박스 리스너 설정
    private void setupActivitySortFilters() {
        // chkHisDateOrder: 날짜순 (ASC)
        // chkHisLatest: 최신순 (DESC)
        chkHisDateOrder.addActionListener(e -> {
            if (chkHisDateOrder.isSelected()) {
                chkHisLatest.setSelected(false);
                loadHistoryTable("ASC");
            }
        });

        chkHisLatest.addActionListener(e -> {
            if (chkHisLatest.isSelected()) {
                chkHisDateOrder.setSelected(false);
                loadHistoryTable("DESC");
            }
        });

        // 기본값: 최신순 선택
        chkHisLatest.setSelected(true);
    }

    // 스케줄 정렬 체크박스 리스너 설정
    private void setupScheduleSortFilters() {
        chkScheLatest.addActionListener(e -> {
            if (chkScheLatest.isSelected()) {
                chkScheDateOrder.setSelected(false);
                loadScheduleTable("DESC");
            }
        });

        chkScheDateOrder.addActionListener(e -> {
            if (chkScheDateOrder.isSelected()) {
                chkScheLatest.setSelected(false);
                loadScheduleTable("ASC");
            }
        });

        // 기본값: 최신순 선택
        chkScheLatest.setSelected(true);

    }

    private void setupDuesSortFilters() {
        chkDuesLatest.addActionListener(e -> {
            if (chkDuesLatest.isSelected()) {
                chkDuesDateOrder.setSelected(false);
                loadDuesHistory("DESC");
            }
        });

        chkDuesDateOrder.addActionListener(e -> {
            if (chkDuesDateOrder.isSelected()) {
                chkDuesLatest.setSelected(false);
                loadDuesHistory("ASC");
            }
        });

        // 기본값: 최신순 선택
        chkDuesLatest.setSelected(true);
    }

    // role 영어를 한글로 변환
    private String convertRoleToKorean(String role) {
        switch (role) {
            case "admin":
                return "관리자";
            case "president":
                return "부장";
            case "member":
                return "회원";
            default:
                return role;
        }
    }

    // role 한글을 영어로 변환
    private String convertRoleToEnglish(String koreanRole) {
        switch (koreanRole) {
            case "관리자":
                return "admin";
            case "부장":
                return "president";
            case "평회원":
            case "회원":
                return "member";
            default:
                return koreanRole;
        }
    }

    // 현재 사용자가 관리자 권한(admin 또는 president)을 가지고 있는지 확인
    private boolean hasAdminPrivilege() {
        String role = UserSession.getRole();
        return "admin".equals(role) || "president".equals(role);
    }

    private void deleteMember(int userId) {
        String sql = "DELETE FROM users WHERE id=?";

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, userId);

            int affected = pstmt.executeUpdate();
            if (affected > 0) {
                JOptionPane.showMessageDialog(this, "회원이 삭제되었습니다.");
            } else {
                JOptionPane.showMessageDialog(this, "회원 삭제에 실패했습니다.");
            }

        } catch (SQLException e) {
            System.err.println("회원 삭제 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "회원 삭제 중 오류가 발생했습니다: " + e.getMessage());
        }
    }

    private void changeRole(int userId, String newRole) {
        if (!hasAdminPrivilege()) {
            JOptionPane.showMessageDialog(this, "직책 변경 권한이 없습니다.");
            return;
        }

        String sql = "UPDATE users SET role=? WHERE id=?";

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, newRole);
            pstmt.setInt(2, userId);

            int affected = pstmt.executeUpdate();
            if (affected > 0) {
                JOptionPane.showMessageDialog(this, "직책이 변경되었습니다.");
            } else {
                JOptionPane.showMessageDialog(this, "직책 변경에 실패했습니다.");
            }

        } catch (SQLException e) {
            System.err.println("직책 변경 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "직책 변경 중 오류가 발생했습니다: " + e.getMessage());
        }
    }

    public void loadScheduleTable(){
        loadScheduleTable("DESC"); // 기본값: 최신순
    }

    // 스케줄 테이블 로드 (정렬: ASC=날짜순, DESC=최신순)
    public void loadScheduleTable(String sortOrder){
        scheduleIds.clear();

        DefaultTableModel model = (DefaultTableModel) ScheTable.getModel();
        model.setRowCount(0); // 테이블 완전 초기화

        String sql = "SELECT id, schedule_date, location, member_count, description, participants, completed " +
                     "FROM schedules ORDER BY schedule_date " + sortOrder;

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {

                // 실제 id 저장
                scheduleIds.add(rs.getInt("id"));

                // 완료 여부를 한글로 변환
                boolean completed = rs.getBoolean("completed");
                String completedText = completed ? "완료" : "미완료";

                // 테이블에 데이터 행 추가
                model.addRow(new Object[]{
                    rs.getString("schedule_date"),
                    rs.getString("location"),
                    rs.getString("member_count"),
                    rs.getString("description"),
                    rs.getString("participants"),
                    completedText
                });
            }

        } catch (SQLException e) {
            System.err.println("스케줄 테이블 로드 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
        }

        // 테이블 새로고침 시 버튼 텍스트 초기화
        btnPartInsert.setText("인원 등록");
    }
    // 활동 내역 테이블 로드
    private void loadHistoryTable() {
        loadHistoryTable("DESC");
    }

    private void loadHistoryTable(String sortOrder) {
        activityIds.clear();

        DefaultTableModel model = (DefaultTableModel) HisTable.getModel();
        model.setRowCount(0);

        // 정렬 방식에 따라 SQL 쿼리 구성
        String sql = "SELECT id, activity_date, location, member_count, description, participants " +
                     "FROM activities ORDER BY activity_date " + sortOrder;

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                // 실제 id 저장
                activityIds.add(rs.getInt("id"));

                // 테이블에 데이터 행 추가
                model.addRow(new Object[]{
                    rs.getString("activity_date"),
                    rs.getString("location"),
                    rs.getInt("member_count"),
                    rs.getString("description"),
                    rs.getString("participants")
                });
            }

        } catch (SQLException e) {
            System.err.println("활동 내역 테이블 로드 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
        }
    }
    private void loadDuesHistory() {
        loadDuesHistory("DESC");
    }

    private void loadDuesHistory(String sortOrder) {
        duesIds.clear();
        DefaultTableModel model = (DefaultTableModel) DuesTable.getModel();
        model.setRowCount(0);

        String sql = "SELECT id, usage_date, location, representative, description, amount " +
                     "FROM dues ORDER BY usage_date " + sortOrder;

        // 현재 총 회비와 사용 금액 계산
        int currentDues = getCurrentDues();
        int usedAmount = calculateUsedAmount();
        int currentBalance = currentDues - usedAmount;

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            ArrayList<Object[]> rows = new ArrayList<>();
            ArrayList<Integer> ids = new ArrayList<>();

            while (rs.next()) {
                ids.add(rs.getInt("id"));
                rows.add(new Object[]{
                    rs.getString("usage_date"),
                    rs.getString("location"),
                    rs.getString("representative"),
                    rs.getString("description"),
                    rs.getInt("amount"),
                    null  // 잔액은 나중에 계산
                });
            }

            // 잔액 계산
            if ("DESC".equals(sortOrder)) {
                // 최신순: 현재 잔액부터 역으로 계산
                int balance = currentBalance;
                for (int i = 0; i < rows.size(); i++) {
                    duesIds.add(ids.get(i));
                    Object[] row = rows.get(i);
                    row[5] = balance;
                    balance += (int) row[4];
                    model.addRow(row);
                }
            } else {
                // 날짜순: 초기 잔액부터 순차적으로 계산
                int balance = currentDues;
                for (int i = 0; i < rows.size(); i++) {
                    duesIds.add(ids.get(i));
                    Object[] row = rows.get(i);
                    balance -= (int) row[4];
                    row[5] = balance;
                    model.addRow(row);
                }
            }

        } catch (SQLException e) {
            System.err.println("회비 내역 로드 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // 회비 날짜 필드에 오늘 날짜 설정
    private void setDefaultDuesDate() {
        java.time.LocalDate today = java.time.LocalDate.now();
        txtDuesYear.setText(String.valueOf(today.getYear()));
        txtDuesMonth.setText(String.valueOf(today.getMonthValue()));
        txtDuesDay.setText(String.valueOf(today.getDayOfMonth()));
    }

    // 스케줄 날짜 필드에 오늘 날짜 설정
    private void setDefaultScheDate() {
        java.time.LocalDate today = java.time.LocalDate.now();
        txtScheYear.setText(String.valueOf(today.getYear()));
        txtScheMonth.setText(String.valueOf(today.getMonthValue()));
        txtScheDay.setText(String.valueOf(today.getDayOfMonth()));
    }

    // dues_settings에서 현재 총 회비 조회
    private int getCurrentDues() {
        String sql = "SELECT current_dues FROM dues_settings WHERE id=1";

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            if (rs.next()) {
                return rs.getInt("current_dues");
            }

        } catch (SQLException e) {
            System.err.println("현재 회비 조회 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
        }

        return 0;
    }

    // 이번달 회비 계산 (학생 수 × 10,000원)
    private int calculateMonthlyDues() {
        String sql = "SELECT COUNT(*) as member_count FROM users WHERE role IN ('president', 'member')";

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            if (rs.next()) {
                int memberCount = rs.getInt("member_count");
                return memberCount * 10000;
            }

        } catch (SQLException e) {
            System.err.println("회원 수 조회 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
        }

        return 0;
    }

    // 사용 금액 합계 계산
    private int calculateUsedAmount() {
        String sql = "SELECT COALESCE(SUM(amount), 0) as total_used FROM dues";

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            if (rs.next()) {
                return rs.getInt("total_used");
            }

        } catch (SQLException e) {
            System.err.println("사용 금액 조회 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
        }

        return 0;
    }

    // 잔여 회비 계산
    private int calculateBalance() {
        return getCurrentDues() - calculateUsedAmount();
    }

    // 이번달 회비 입금 처리 (dues_settings 업데이트)
    private void addMonthlyDues(int amount) {
        if (!hasAdminPrivilege()) {
            JOptionPane.showMessageDialog(this, "회비 입금 권한이 없습니다.");
            return;
        }

        String sql = "UPDATE dues_settings SET current_dues = current_dues + ? WHERE id=1";

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, amount);

            int affected = pstmt.executeUpdate();
            if (affected > 0) {
                JOptionPane.showMessageDialog(this,
                    String.format("%,d원이 입금되었습니다!", amount));
                updateDuesLabels();
            } else {
                JOptionPane.showMessageDialog(this, "입금 처리에 실패했습니다.");
            }

        } catch (SQLException e) {
            System.err.println("회비 입금 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "회비 입금 중 오류가 발생했습니다: " + e.getMessage());
        }
    }

    // 회비 라벨 업데이트 (회원 수, 이번달 회비, 잔여 회비)
    private void updateDuesLabels() {
        int monthlyDues = calculateMonthlyDues();
        int balance = calculateBalance();

        lblTotalDues.setText(String.format("%,d원", monthlyDues));
        lblRemainDues.setText(String.format("%,d원", balance));
    }

    // 대표자 선택용 콤보박스에 회원 목록 로드
    private void loadMembersForRepresentative() {
        cbxDuesRepresentive.removeAllItems();

        String sql = "SELECT name FROM users ORDER BY name";

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                cbxDuesRepresentive.addItem(rs.getString("name"));
            }

        } catch (SQLException e) {
            System.err.println("회원 목록 로드 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // 회비 사용 내역 등록 (날짜 수정 가능)
    private void registerDues(String date, String location, String representative,
                              String description, int amount) {
        if (!hasAdminPrivilege()) {
            JOptionPane.showMessageDialog(this, "회비 등록 권한이 없습니다.");
            return;
        }

        String sql = "INSERT INTO dues (usage_date, location, representative, description, amount, created_by) " +
                     "VALUES (?, ?, ?, ?, ?, ?)";

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, date);
            pstmt.setString(2, location);
            pstmt.setString(3, representative);
            pstmt.setString(4, description);
            pstmt.setInt(5, amount);
            pstmt.setString(6, UserSession.getUserId());

            int affected = pstmt.executeUpdate();
            if (affected > 0) {
                JOptionPane.showMessageDialog(this, "회비 사용 내역이 등록되었습니다!");

                clearDuesInputs();
                loadDuesHistory();
                updateDuesLabels();
            } else {
                JOptionPane.showMessageDialog(this, "회비 등록에 실패했습니다.");
            }

        } catch (SQLException e) {
            System.err.println("회비 등록 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "회비 등록 중 오류가 발생했습니다: " + e.getMessage());
        }
    }

    // 회비 입력 필드 초기화 (날짜는 오늘로 재설정)
    private void clearDuesInputs() {
        setDefaultDuesDate(); // 날짜를 오늘로 재설정
        txtDuesLocation.setText("");
        txtDuesDescription.setText("");
        txtDuesAmount.setText("");
        if (cbxDuesRepresentive.getItemCount() > 0) {
            cbxDuesRepresentive.setSelectedIndex(0);
        }
    }

    // 회비 사용 내역 삭제
    private void deleteDues(int duesId) {
        if (!hasAdminPrivilege()) {
            JOptionPane.showMessageDialog(this, "회비 삭제 권한이 없습니다.");
            return;
        }

        String sql = "DELETE FROM dues WHERE id=?";

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, duesId);

            int affected = pstmt.executeUpdate();
            if (affected > 0) {
                JOptionPane.showMessageDialog(this, "회비 내역이 삭제되었습니다.");
            } else {
                JOptionPane.showMessageDialog(this, "회비 삭제에 실패했습니다.");
            }

        } catch (SQLException e) {
            System.err.println("회비 삭제 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "회비 삭제 중 오류가 발생했습니다: " + e.getMessage());
        }
    }
    
    //로그아웃 버튼
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        UserSession.clear();
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    //인원 관리 탭 새로고침 버튼
    private void btnMemRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemRefreshActionPerformed
        refreshMemberTable();
        JOptionPane.showMessageDialog(this, "회원 목록이 새로고침되었습니다.");
    }//GEN-LAST:event_btnMemRefreshActionPerformed
    //인원 관리 탭 삽입 버튼
    private void btnMemInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemInsertActionPerformed
        if (!hasAdminPrivilege()) {
            JOptionPane.showMessageDialog(this, "회원 추가 권한이 없습니다.");
            return;
        }

        // 회원 추가 다이얼로그 열기 (MainFrame에서 호출됨을 표시)
        new SignUpFrame(true).setVisible(true);
    }//GEN-LAST:event_btnMemInsertActionPerformed
    //인원 관리 탭 변경 버튼
    private void btnMemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemUpdateActionPerformed
        // 선택된 행 확인
        int selectedRow = MemTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "수정할 회원을 선택해주세요.");
            return;
        }

        // 선택된 회원 정보 가져오기
        int userId = (int) MemTable.getValueAt(selectedRow, 0);
        String username = (String) MemTable.getValueAt(selectedRow, 1);
        String name = (String) MemTable.getValueAt(selectedRow, 2);
        String studentId = (String) MemTable.getValueAt(selectedRow, 3);
        String gender = (String) MemTable.getValueAt(selectedRow, 4);
        String role = (String) MemTable.getValueAt(selectedRow, 5);
        String birthDate = (String) MemTable.getValueAt(selectedRow, 6);

        // 권한 체크: admin 또는 본인만 가능
        String currentUserRole = UserSession.getRole();
        String currentUsername = UserSession.getUserId();

        if (!("admin".equals(currentUserRole)) && !username.equals(currentUsername)) {
            JOptionPane.showMessageDialog(this,
                "본인 또는 관리자만 회원 정보를 수정할 수 있습니다.");
            return;
        }

        // SignUpFrame을 수정 모드로 열기
        new SignUpFrame(userId, username, name, studentId, gender, birthDate, "").setVisible(true);

        // 테이블 새로고침 (SignUpFrame 닫힌 후 자동으로 반영되지 않으므로 새로고침 버튼 사용 필요)
    }//GEN-LAST:event_btnMemUpdateActionPerformed
    //인원 관리 직책 변경 버튼
    private void btnRoleChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoleChangeActionPerformed
        if (!hasAdminPrivilege()) {
            JOptionPane.showMessageDialog(this, "직책 변경 권한이 없습니다.");
            return;
        }

        // 선택된 행 확인
        int selectedRow = MemTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "직책을 변경할 회원을 선택해주세요.");
            return;
        }

        // 선택된 회원 정보 가져오기
        int userId = (int) MemTable.getValueAt(selectedRow, 0);
        String username = (String) MemTable.getValueAt(selectedRow, 1);
        String name = (String) MemTable.getValueAt(selectedRow, 2);
        String currentRole = (String) MemTable.getValueAt(selectedRow, 5);

        // 직책 선택
        String[] roles = {"admin", "president", "member"};
        String[] roleLabels = {"관리자", "부장", "평회원"};

        String selectedRoleLabel = (String) JOptionPane.showInputDialog(
                this,
                name + "(" + username + ")의 직책을 변경하세요:",
                "직책 변경",
                JOptionPane.QUESTION_MESSAGE,
                null,
                roleLabels,
                currentRole
        );

        if (selectedRoleLabel == null) {
            return; // 취소
        }

        String newRole = convertRoleToEnglish(selectedRoleLabel);
        changeRole(userId, newRole);
        refreshMemberTable();
    }//GEN-LAST:event_btnRoleChangeActionPerformed
    //인원 관리 탭 삭제 버튼
    private void btnMemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemDeleteActionPerformed
        if (!hasAdminPrivilege()) {
            JOptionPane.showMessageDialog(this, "회원 삭제 권한이 없습니다.");
            return;
        }

        // 선택된 행 확인
        int selectedRow = MemTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "삭제할 회원을 선택해주세요.");
            return;
        }

        // 선택된 회원 정보 가져오기
        int userId = (int) MemTable.getValueAt(selectedRow, 0);
        String username = (String) MemTable.getValueAt(selectedRow, 1);
        String name = (String) MemTable.getValueAt(selectedRow, 2);

        // 삭제 확인
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "정말로 '" + name + "' (" + username + ") 회원을 삭제하시겠습니까?",
                "회원 삭제 확인",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        deleteMember(userId);
        refreshMemberTable();
    }//GEN-LAST:event_btnMemDeleteActionPerformed
    
    //스케줄 관리 탭 새로고침 버튼
    private void btnScheRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheRefreshActionPerformed
        loadScheduleTable();
        JOptionPane.showMessageDialog(this, "스케줄이 새로고침되었습니다.");
    }//GEN-LAST:event_btnScheRefreshActionPerformed
    //스케줄 관리 탭 일정 등록 버튼
    private void btnScheInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheInsertActionPerformed
        String year = txtScheYear.getText().trim();
        String month = txtScheMonth.getText().trim();
        String day = txtScheDay.getText().trim();
        String date = year + "-" + month + "-" + day;
        String location = snpScheLocation.getText().trim();
        String description = snpScheDescription.getText().trim();
        boolean completed = chkScheCompleted.isSelected();

        if (year.isEmpty() || month.isEmpty() || day.isEmpty()) {
            JOptionPane.showMessageDialog(this, "날짜를 모두 입력해주세요.");
            this.requestFocusInWindow();
            return;
        }
        if (location.isEmpty()) {
            JOptionPane.showMessageDialog(this, "장소를 입력해주세요.");
            this.requestFocusInWindow();
            return;
        }
        if (description.isEmpty()) {
            JOptionPane.showMessageDialog(this, "활동 내용을 입력해주세요.");
            this.requestFocusInWindow();
            return;
        }

        // 편집 모드에 따라 등록 또는 수정 수행
        if (isEditMode) {
            // 수정 모드: 기존 스케줄 업데이트
            updateSchedule(editingScheduleId, date, location, description, completed);
        } else {
            // 등록 모드: 새 스케줄 등록 (인원수는 0으로 시작, 참가자 추가 시 자동 업데이트)
            registerSchedule(date, location, 0, description, completed);
        }

        clearScheduleInputs();
        loadScheduleTable();
    }//GEN-LAST:event_btnScheInsertActionPerformed

    // 스케줄 등록 (참가자 없이)
    private void registerSchedule(String date, String location, int memberCount,
                                  String description, boolean completed) {
        // 완료 체크 시 바로 activities에만 저장
        if (completed) {
            String sql = "INSERT INTO activities (activity_date, location, member_count, description, participants) " +
                         "VALUES (?, ?, ?, ?, ?)";

            try (Connection conn = new DBConnection().getConnection();
                 PreparedStatement pstmt = conn.prepareStatement(sql)) {

                pstmt.setString(1, date);
                pstmt.setString(2, location);
                pstmt.setInt(3, memberCount);
                pstmt.setString(4, description);
                pstmt.setString(5, ""); // 참가자 없음

                int affected = pstmt.executeUpdate();

                if (affected > 0) {
                    JOptionPane.showMessageDialog(this, "완료된 활동이 활동 내역에 등록되었습니다!");
                    loadHistoryTable(); // 활동 내역 테이블 새로고침
                } else {
                    JOptionPane.showMessageDialog(this, "활동 등록에 실패했습니다.");
                }

            } catch (SQLException e) {
                System.err.println("활동 등록 중 오류 발생: " + e.getMessage());
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "활동 등록 중 오류가 발생했습니다: " + e.getMessage());
            }

        } else {
            // 미완료 스케줄은 schedules에 저장
            String sql = "INSERT INTO schedules (schedule_date, location, member_count, description, completed) " +
                         "VALUES (?, ?, ?, ?, ?)";

            try (Connection conn = new DBConnection().getConnection();
                 PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

                pstmt.setString(1, date);
                pstmt.setString(2, location);
                pstmt.setInt(3, memberCount);
                pstmt.setString(4, description);
                pstmt.setBoolean(5, completed);

                int affected = pstmt.executeUpdate();

                if (affected > 0) {
                    JOptionPane.showMessageDialog(this, "일정이 등록되었습니다!");
                } else {
                    JOptionPane.showMessageDialog(this, "일정 등록에 실패했습니다.");
                }

            } catch (SQLException e) {
                System.err.println("스케줄 등록 중 오류 발생: " + e.getMessage());
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "일정 등록 중 오류가 발생했습니다: " + e.getMessage());
            }
        }
    }

    // 스케줄 입력 필드 초기화 (날짜는 오늘로 재설정)
    private void clearScheduleInputs() {
        setDefaultScheDate(); // 날짜를 오늘로 재설정
        snpScheLocation.setText("");
        snpScheDescription.setText("");
        chkScheCompleted.setSelected(false);

        // 수정 모드 해제
        isEditMode = false;
        editingScheduleId = -1;
        btnScheInsert.setText("일정 등록"); // 버튼 텍스트 원래대로
        btnPartInsert.setText("인원 등록"); // 인원 버튼 텍스트 원래대로
    }

    // 선택한 스케줄을 입력 필드에 로드 (수정 모드)
    private void loadScheduleForEdit(int scheduleId) {
        String sql = "SELECT schedule_date, location, description, completed FROM schedules WHERE id=?";

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, scheduleId);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                // 날짜 파싱
                String date = rs.getString("schedule_date");
                String[] dateParts = date.split("-");
                txtScheYear.setText(dateParts[0]);
                txtScheMonth.setText(dateParts[1]);
                txtScheDay.setText(dateParts[2]);

                // 기타 정보 로드
                snpScheLocation.setText(rs.getString("location"));
                snpScheDescription.setText(rs.getString("description"));
                chkScheCompleted.setSelected(rs.getBoolean("completed"));

                // 수정 모드 활성화
                isEditMode = true;
                editingScheduleId = scheduleId;
                btnScheInsert.setText("일정 수정 완료"); // 버튼 텍스트 변경
                btnPartInsert.setText("인원 수정"); // 인원 버튼 텍스트 변경

                JOptionPane.showMessageDialog(this, "수정할 데이터를 불러왔습니다. 수정 후 '일정 수정 완료' 버튼을 눌러주세요.");
            }

        } catch (SQLException e) {
            System.err.println("스케줄 로드 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "스케줄 로드 중 오류가 발생했습니다: " + e.getMessage());
        }
    }

    // 스케줄 업데이트
    private void updateSchedule(int scheduleId, String date, String location, String description, boolean completed) {
        // 완료 체크 시 activities로 이동
        if (completed) {
            // 먼저 스케줄 정보 업데이트 (날짜, 장소, 내용)
            String updateSql = "UPDATE schedules SET schedule_date=?, location=?, description=? WHERE id=?";

            try (Connection conn = new DBConnection().getConnection();
                 PreparedStatement pstmt = conn.prepareStatement(updateSql)) {

                pstmt.setString(1, date);
                pstmt.setString(2, location);
                pstmt.setString(3, description);
                pstmt.setInt(4, scheduleId);

                pstmt.executeUpdate();

            } catch (SQLException e) {
                System.err.println("스케줄 업데이트 중 오류 발생: " + e.getMessage());
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "일정 수정 중 오류가 발생했습니다: " + e.getMessage());
                return;
            }

            // activities로 이동 (schedules에서 삭제)
            completeSchedule(scheduleId);
            JOptionPane.showMessageDialog(this, "일정이 완료되어 활동 내역으로 이동되었습니다!");
            loadScheduleTable(); // 스케줄 테이블 새로고침
            loadHistoryTable(); // 활동 내역 테이블 새로고침
            clearScheduleInputs(); // 입력 필드 초기화 및 수정 모드 해제

        } else {
            // 완료 체크 안 함: 일반 업데이트
            String sql = "UPDATE schedules SET schedule_date=?, location=?, description=?, completed=? WHERE id=?";

            try (Connection conn = new DBConnection().getConnection();
                 PreparedStatement pstmt = conn.prepareStatement(sql)) {

                pstmt.setString(1, date);
                pstmt.setString(2, location);
                pstmt.setString(3, description);
                pstmt.setBoolean(4, completed);
                pstmt.setInt(5, scheduleId);

                int affected = pstmt.executeUpdate();
                if (affected > 0) {
                    JOptionPane.showMessageDialog(this, "일정이 수정되었습니다!");
                    loadScheduleTable(); // 테이블 새로고침
                    clearScheduleInputs(); // 입력 필드 초기화 및 수정 모드 해제
                } else {
                    JOptionPane.showMessageDialog(this, "일정 수정에 실패했습니다.");
                }

            } catch (SQLException e) {
                System.err.println("스케줄 수정 중 오류 발생: " + e.getMessage());
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "일정 수정 중 오류가 발생했습니다: " + e.getMessage());
            }
        }
    }

    //스케줄 관리 탭 일정 삭제 버튼
    private void btnScheDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheDeleteActionPerformed
        int row = ScheTable.getSelectedRow();

        if (row == -1 || row >= scheduleIds.size()) {
            JOptionPane.showMessageDialog(this, "유효한 일정을 선택하세요.");
            return;
        }

        int scheduleId = scheduleIds.get(row);

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "정말로 삭제하시겠습니까?",
                "일정 삭제",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        String sql = "DELETE FROM schedules WHERE id = ?";

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, scheduleId);
            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "일정이 삭제되었습니다.");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "삭제 중 오류 발생: " + ex.getMessage());
            ex.printStackTrace();
        }

        scheduleIds.clear();
        loadScheduleTable();
    }//GEN-LAST:event_btnScheDeleteActionPerformed
    
    //활동 내역 탭 새로고침 버튼
    private void btnHisRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHisRefreshActionPerformed
        // 현재 선택된 정렬 방식으로 새로고침
        String sortOrder = chkHisDateOrder.isSelected() ? "ASC" : "DESC";
        loadHistoryTable(sortOrder);
        JOptionPane.showMessageDialog(this, "활동 내역이 새로고침되었습니다.");
    }//GEN-LAST:event_btnHisRefreshActionPerformed

   //활동 내역 탭 활동 삭제 버튼
    private void btnHisDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHisDeleteActionPerformed
        if (!hasAdminPrivilege()) {
            JOptionPane.showMessageDialog(this, "활동 삭제 권한이 없습니다.");
            return;
        }

        // 선택된 행 확인
        int selectedRow = HisTable.getSelectedRow();
        if (selectedRow == -1 || selectedRow >= activityIds.size()) {
            JOptionPane.showMessageDialog(this, "삭제할 활동을 선택해주세요.");
            return;
        }

        // activityIds에서 실제 ID 가져오기
        int activityId = activityIds.get(selectedRow);

        // 삭제 확인
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "정말로 이 활동 내역을 삭제하시겠습니까?",
                "활동 삭제 확인",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        deleteActivity(activityId);

        String sortOrder = chkHisDateOrder.isSelected() ? "ASC" : "DESC";
        loadHistoryTable(sortOrder);
    }//GEN-LAST:event_btnHisDeleteActionPerformed

    // 활동 내역 삭제
    private void deleteActivity(int activityId) {
        String sql = "DELETE FROM activities WHERE id=?";

        try (Connection conn = new DBConnection().getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, activityId);

            int affected = pstmt.executeUpdate();
            if (affected > 0) {
                JOptionPane.showMessageDialog(this, "활동 내역이 삭제되었습니다.");
            } else {
                JOptionPane.showMessageDialog(this, "활동 내역 삭제에 실패했습니다.");
            }

        } catch (SQLException e) {
            System.err.println("활동 내역 삭제 중 오류 발생: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "활동 내역 삭제 중 오류가 발생했습니다: " + e.getMessage());
        }
    }

    //회비 관리 탭 새로고침 버튼
    private void btnDuesUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuesUpdateActionPerformed
        loadDuesHistory();
        updateDuesLabels();
        JOptionPane.showMessageDialog(this, "회비 내역이 새로고침되었습니다.");
    }//GEN-LAST:event_btnDuesUpdateActionPerformed
    //회비 관리 탭 내역 추가 버튼 (사용 내역 등록)
    private void btnDuesInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuesInsertActionPerformed
        if (!hasAdminPrivilege()) {
            JOptionPane.showMessageDialog(this, "회비 등록 권한이 없습니다.");
            return;
        }

        String year = txtDuesYear.getText().trim();
        String month = txtDuesMonth.getText().trim();
        String day = txtDuesDay.getText().trim();
        String date = year + "-" + month + "-" + day;
        String location = txtDuesLocation.getText().trim();
        String representative = (String) cbxDuesRepresentive.getSelectedItem();
        String description = txtDuesDescription.getText().trim();
        String amountStr = txtDuesAmount.getText().trim();

        if (year.isEmpty() || month.isEmpty() || day.isEmpty()) {
            JOptionPane.showMessageDialog(this, "날짜를 입력해주세요.");
            return;
        }
        if (location.isEmpty()) {
            JOptionPane.showMessageDialog(this, "장소를 입력해주세요.");
            return;
        }
        if (representative == null || representative.isEmpty()) {
            JOptionPane.showMessageDialog(this, "대표자를 선택해주세요.");
            return;
        }
        if (description.isEmpty()) {
            JOptionPane.showMessageDialog(this, "사용 내역을 입력해주세요.");
            return;
        }
        if (amountStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "금액을 입력해주세요.");
            return;
        }

        // 금액 파싱
        int amount;
        try {
            amount = Integer.parseInt(amountStr);
            if (amount <= 0) {
                JOptionPane.showMessageDialog(this, "금액은 0보다 커야 합니다.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "올바른 금액을 입력해주세요.");
            return;
        }

        registerDues(date, location, representative, description, amount);
    }//GEN-LAST:event_btnDuesInsertActionPerformed
    //회비 관리 탭 내역 삭제 버튼
    private void btnDuesDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuesDeleteActionPerformed
        if (!hasAdminPrivilege()) {
            JOptionPane.showMessageDialog(this, "회비 삭제 권한이 없습니다.");
            return;
        }

        // 선택된 행 확인
        int selectedRow = DuesTable.getSelectedRow();
        if (selectedRow == -1 || selectedRow >= duesIds.size()) {
            JOptionPane.showMessageDialog(this, "삭제할 회비 내역을 선택해주세요.");
            return;
        }

        // duesIds에서 실제 ID 가져오기
        int duesId = duesIds.get(selectedRow);

        // 삭제 확인
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "정말로 이 회비 내역을 삭제하시겠습니까?",
                "회비 삭제 확인",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        deleteDues(duesId);
        loadDuesHistory();
        updateDuesLabels();
    }//GEN-LAST:event_btnDuesDeleteActionPerformed
    
    //스케줄 관리 탭 인원 등록/수정 버튼
    private void btnPartInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartInsertActionPerformed

        // 테이블에서 선택된 행 확인
        int selectedRow = ScheTable.getSelectedRow();

        if (selectedRow == -1 || selectedRow >= scheduleIds.size()) {
            JOptionPane.showMessageDialog(this,
                "일정을 먼저 등록해 주세요.");
            this.requestFocusInWindow();
            return;
        }

        // 선택된 스케줄의 ID 가져오기
        int scheduleId = scheduleIds.get(selectedRow);

        // 참가자 입력 프레임 열기
        ParticipantsFrame frame = new ParticipantsFrame(scheduleId);
        frame.setVisible(true);

        // 스케줄 테이블 새로고침
        loadScheduleTable();
    }//GEN-LAST:event_btnPartInsertActionPerformed

    //스케줄 관리 탭에서 행을 클릭했을 때
    private void ScheTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheTableMouseClicked
        int row = ScheTable.getSelectedRow();

        // row가 실제 데이터보다 크면 무시
        if (row >= scheduleIds.size() || row == -1) {
            return;
        }

        // 행이 선택되면 "인원 등록" 버튼을 "인원 수정"으로 변경
        btnPartInsert.setText("인원 수정");
    }//GEN-LAST:event_ScheTableMouseClicked

    //회비 입금 버튼
    private void btnDuesDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuesDepositActionPerformed
        if (!hasAdminPrivilege()) {
            JOptionPane.showMessageDialog(this, "회비 입금 권한이 없습니다.");
            return;
        }

        // 이번달 회비 계산
        int monthlyDues = calculateMonthlyDues();

        // 입금 확인 다이얼로그
        int confirm = JOptionPane.showConfirmDialog(this,
            String.format("이번달 회비 %,d원을 입금하시겠습니까?", monthlyDues),
            "회비 입금 확인",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            addMonthlyDues(monthlyDues);
        }
    }//GEN-LAST:event_btnDuesDepositActionPerformed

    private void btnScheUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheUpdateActionPerformed
        // 선택된 행 가져오기
        int selectedRow = ScheTable.getSelectedRow();
        if (selectedRow == -1 || selectedRow >= scheduleIds.size()) {
            JOptionPane.showMessageDialog(this, "수정할 일정을 선택해주세요.");
            return;
        }

        // 선택된 스케줄 ID 가져오기
        int scheduleId = scheduleIds.get(selectedRow);

        // 수정 모드로 전환하고 데이터 로드
        loadScheduleForEdit(scheduleId);
    }//GEN-LAST:event_btnScheUpdateActionPerformed
    // 스케줄 완료 처리 (트랜잭션): schedules → activities 이동
    public void completeSchedule(int scheduleId) {
        Connection conn = null;
        try {
            conn = new DBConnection().getConnection();
            conn.setAutoCommit(false); // 트랜잭션 시작

            // schedules에서 데이터 조회
            String selectSql = "SELECT schedule_date, location, member_count, description, participants " +
                              "FROM schedules WHERE id=?";

            String activityDate = null;
            String location = null;
            int memberCount = 0;
            String description = null;
            String participants = null;

            try (PreparedStatement selectStmt = conn.prepareStatement(selectSql)) {
                selectStmt.setInt(1, scheduleId);
                ResultSet rs = selectStmt.executeQuery();

                if (rs.next()) {
                    activityDate = rs.getString("schedule_date");
                    location = rs.getString("location");
                    memberCount = rs.getInt("member_count");
                    description = rs.getString("description");
                    participants = rs.getString("participants");
                } else {
                    throw new SQLException("스케줄을 찾을 수 없습니다.");
                }
            }

            // activities 테이블에 INSERT
            String insertSql = "INSERT INTO activities (activity_date, location, member_count, description, participants) " +
                              "VALUES (?, ?, ?, ?, ?)";

            try (PreparedStatement insertStmt = conn.prepareStatement(insertSql)) {
                insertStmt.setString(1, activityDate);
                insertStmt.setString(2, location);
                insertStmt.setInt(3, memberCount);
                insertStmt.setString(4, description);
                insertStmt.setString(5, participants);

                insertStmt.executeUpdate();
            }

            // schedules에서 DELETE (활동 내역으로 완전히 이동)
            String deleteSql = "DELETE FROM schedules WHERE id=?";

            try (PreparedStatement deleteStmt = conn.prepareStatement(deleteSql)) {
                deleteStmt.setInt(1, scheduleId);
                deleteStmt.executeUpdate();
            }

            conn.commit();
            System.out.println("스케줄 완료 처리 성공 (트랜잭션 완료)");

            loadScheduleTable();
            loadHistoryTable();

        } catch (SQLException e) {
            // 트랜잭션 롤백
            try {
                if (conn != null) {
                    conn.rollback();
                    System.err.println("트랜잭션 롤백됨");
                }
            } catch (SQLException rollbackEx) {
                rollbackEx.printStackTrace();
            }

            System.err.println("스케줄 완료 처리 중 오류: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "스케줄 완료 처리 중 오류가 발생했습니다: " + e.getMessage());

        } finally {
            try {
                if (conn != null) {
                    conn.setAutoCommit(true); // 자동 커밋 모드 복원
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DuesPanel;
    private javax.swing.JTable DuesTable;
    private javax.swing.JPanel HisPanel;
    private javax.swing.JTable HisTable;
    private javax.swing.JPanel MemPanel;
    private javax.swing.JTable MemTable;
    private javax.swing.JPanel SchePanel;
    private javax.swing.JTable ScheTable;
    private javax.swing.JButton btnDuesDelete;
    private javax.swing.JButton btnDuesDeposit;
    private javax.swing.JButton btnDuesInsert;
    private javax.swing.JButton btnDuesUpdate;
    private javax.swing.JButton btnHisDelete;
    private javax.swing.JButton btnHisRefresh;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMemDelete;
    private javax.swing.JButton btnMemInsert;
    private javax.swing.JButton btnMemRefresh;
    private javax.swing.JButton btnMemUpdate;
    private javax.swing.JButton btnPartInsert;
    private javax.swing.JButton btnRoleChange;
    private javax.swing.JButton btnScheDelete;
    private javax.swing.JButton btnScheInsert;
    private javax.swing.JButton btnScheRefresh;
    private javax.swing.JButton btnScheUpdate;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JComboBox<String> cbxDuesRepresentive;
    private javax.swing.JCheckBox chkAll;
    private javax.swing.JCheckBox chkDuesDateOrder;
    private javax.swing.JCheckBox chkDuesLatest;
    private javax.swing.JCheckBox chkFemale;
    private javax.swing.JCheckBox chkHisDateOrder;
    private javax.swing.JCheckBox chkHisLatest;
    private javax.swing.JCheckBox chkMale;
    private javax.swing.JCheckBox chkScheCompleted;
    private javax.swing.JCheckBox chkScheDateOrder;
    private javax.swing.JCheckBox chkScheLatest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblRemainDues;
    private javax.swing.JLabel lblTotalDues;
    private javax.swing.JLabel lblUserInfo;
    private javax.swing.JTextArea snpScheDescription;
    private javax.swing.JTextField snpScheLocation;
    private javax.swing.JTextField txtDuesAmount;
    private javax.swing.JTextField txtDuesDay;
    private javax.swing.JTextField txtDuesDescription;
    private javax.swing.JTextField txtDuesLocation;
    private javax.swing.JTextField txtDuesMonth;
    private javax.swing.JTextField txtDuesYear;
    private javax.swing.JTextField txtScheDay;
    private javax.swing.JTextField txtScheMonth;
    private javax.swing.JTextField txtScheYear;
    // End of variables declaration//GEN-END:variables
}
